// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SahinTurizim.Data.Concrete.EfCore;

namespace SahinTurizim.Data.Migrations
{
    [DbContext(typeof(SahinTurizimContext))]
    partial class SahinTurizimContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.16");

            modelBuilder.Entity("CityExpedition", b =>
                {
                    b.Property<int>("CitiesCityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExpeditionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CitiesCityId", "ExpeditionId");

                    b.HasIndex("ExpeditionId");

                    b.ToTable("CityExpedition");
                });

            modelBuilder.Entity("SahinTurizim.Entity.Bus", b =>
                {
                    b.Property<int>("BusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BusPlaque")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeatCapasite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("BusId");

                    b.ToTable("Buses");
                });

            modelBuilder.Entity("SahinTurizim.Entity.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CityAbout")
                        .HasColumnType("TEXT");

                    b.Property<string>("CityName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CityNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("CityId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("SahinTurizim.Entity.Expedition", b =>
                {
                    b.Property<int>("ExpeditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndTerminal")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstTerminal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hour")
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecondTerminal")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartTerminal")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThirdTerminal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("ExpeditionId");

                    b.HasIndex("BusId");

                    b.ToTable("Expeditions");
                });

            modelBuilder.Entity("SahinTurizim.Entity.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerSurname")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerToTravel")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerTravel")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpeditionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeronNumber")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("TicketId");

                    b.HasIndex("ExpeditionId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("CityExpedition", b =>
                {
                    b.HasOne("SahinTurizim.Entity.City", null)
                        .WithMany()
                        .HasForeignKey("CitiesCityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SahinTurizim.Entity.Expedition", null)
                        .WithMany()
                        .HasForeignKey("ExpeditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SahinTurizim.Entity.Expedition", b =>
                {
                    b.HasOne("SahinTurizim.Entity.Bus", "Bus")
                        .WithMany("Expeditions")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");
                });

            modelBuilder.Entity("SahinTurizim.Entity.Ticket", b =>
                {
                    b.HasOne("SahinTurizim.Entity.Expedition", "Expedition")
                        .WithMany("Tickets")
                        .HasForeignKey("ExpeditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expedition");
                });

            modelBuilder.Entity("SahinTurizim.Entity.Bus", b =>
                {
                    b.Navigation("Expeditions");
                });

            modelBuilder.Entity("SahinTurizim.Entity.Expedition", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
